### ISSUE TITLE
ARM64/AARCH64 Binaries

### ISSUE THREAD

**Issue by sadnblueish** [svenstaro/miniserve#126]
It shall be nice and time saver for many if precompiled binaries are available for ARM64/AARCH64 platforms.

**Comment by svenstaro** [comment]
Sure, I'll see whether this can be done easily. However, if you want to make a patch then that'd be appreciated. We can use Travis and rustup for cross compiling.

**Comment by giovannikraushaar** [comment]
Any update about that? How could I manually compile on my RockPro 64? I Had a look at the makefile but I saw that all configs are for x86_64

**Comment by svenstaro** [comment]
I'll try putting something together using https://github.com/actions-rs/cargo

**Comment by giovannikraushaar** [comment]
That would be awesome, thank you!

**Comment by giovannikraushaar** [comment]
Dear svenstaro, I've managed to successfully compile miniserve on a RockPro64. The binary should be compatible with all AARCH64 architectures. Here you can download it https://www.swisstransfer.com/d/3843f9c0-62c0-4ac5-9b7a-0ecc69ce812e

Here are the steps I followed:
`sudo pacman -S rustup`
`rustup toolchain install nightly`
`rustup target list`
`clone https://github.com/svenstaro/miniserve.git`
`cd miniserve`
`cargo build --target aarch64-unknown-linux-gnu --release --locked`
`strip target/aarch64-unknown-linux-gnu/release/miniserve`

I could not use upx because otherwise when launching the program it gave me the following error 
`Segmentation fault (core dumped) when trying to run the executable`
