### ISSUE TITLE
上传onedrive问题

### ISSUE THREAD

**Issue by YoloBird** [svenstaro/miniserve#1381]
我在服务器通过rclone挂载了ondedrive，之后把上传的目的文件夹改成了挂载rclone的文件夹，但是我通过上传后发现，首先将文件存在服务器，之后会通过服务器传输到onedrive，这时候问题出现了，我发现上传到onedrive之后，我服务器本地空间应该被释放，但并没有，请问为什么，应该怎么解决？还是说我应该再等待一会

**Comment by svenstaro** [comment]
Please keep it English. I have no idea what this says.

**Comment by YoloBird** [comment]
> Please keep it English. I have no idea what this says.

I mounted OneDrive on the server using rclone, and then changed the destination folder for uploads to the rclone-mounted folder. However, after uploading files, I found that they were first stored on the server and then transferred to OneDrive through the server. At this point, a problem occurred: although I uploaded them to OneDrive successfully, my local space on the server should have been released but it wasn't. Why is this happening? How can I solve it? Or should I wait a while longer?

**Comment by svenstaro** [comment]
I don't think this is a miniserve problem.

**Comment by MrFaul** [comment]
While I have no clue about rclone, I have a hunch why this might happen.
I once had something similar but with unrelated software and the culprit was simply that the file was flagged/tagged as still being opened/used by the OS.

I don't know how miniserve handles "reading" and "closing" files but this could be a possible cause.
Might be worth investigating.
