### ISSUE TITLE
Remove trailing colon

### ISSUE THREAD

**Issue by QuarticCat** [svenstaro/miniserve#1440]
For some reason, Konsole mistakenly include the tailing colon into the detected URL. See the screenshot:

![image](https://github.com/svenstaro/miniserve/assets/70888415/e1b144cf-31bc-4224-b939-2bceafad720d)

Maybe I should report to Konsole? I have no idea if this is a valid URL.

And possibly we can add a newline after QR codes for better readability.

I can submit a PR if you accept that.

**Comment by svenstaro** [comment]
> And possibly we can add a newline after QR codes for better readability.

Happy for a PR for that.

I don't really have an idea where the `:` comes from, though. Does it not happen on other terminals?

**Comment by Atreyagaurav** [comment]
This is not a problem in terminator. 

This is in main.rs 264

                    println!("QR code for {}:", url.green().bold());
                    qr.print();

Since : comes after the url and is separated by ANSI escape sequences, there should be good demarcation for the terminal to understand. Although double-clicking on terminator does include : as part of the word. So maybe that's the problem with konsole. It's easy enough to fix.

**Comment by QuarticCat** [comment]
@Atreyagaurav Thanks for the reply. I found that Konsole doesn't have consistent behavior on this issue. It's more likely Konsole's fault. I've [reported](https://bugs.kde.org/show_bug.cgi?id=489900) there and will close this issue. Sorry for bothering.
