### ISSUE TITLE
Allow clicking the headers to change sort order and sort column

### ISSUE THREAD

**Issue by svenstaro** [svenstaro/miniserve#37]
I suppose this should ignore the command-line provided sort options. Also this should be appended to the URL like so: `localhost:8080?sort=date&order=desc`.

**Comment by boastful-squirrel** [comment]
Good idea ! I think we should solve #34 first, for clarity sake :P

**Comment by svenstaro** [comment]
In fact, now that I think about it, sorting really should be a representational problem and if we went ahead and implemented this then we'd have a sort of duality where you can sort using launch params and by clicking. I think we should only probably allow for letting the end user sort using url parameters and remove the CLI options again (and instead parse the url stuff).

The HTML could just feature some links to click on to change the sort type as well (dirs first vs strictly alphabetical, for instance). Clicking a column header would sort on that and clicking it again would sort the opposite way.

I think that's more intuitive and removes some complexity from the command line options while giving the user more control.

What do you think about that?

**Comment by boastful-squirrel** [comment]
I thought about that too yes, CLI arguments and Javascript-based sorting kind of clash with eachothers. 

The only corner case I see is for people who disable Javascript/use js blocking extensions/use terminal browsers, for those ones, CLI sorting can have a point, but on a more general point of view, I think you're right, it's better to let people sort files the way they want.

Whilst we are at it, a search bar could also be helpful, even if ctrl+f should do the trick since we don't paginate :)

**Comment by svenstaro** [comment]
I'm not talking about JavaScript and I want none in here. The page shall be
regenerated once a column is clicked for sorting.

**Comment by boastful-squirrel** [comment]
Oh, I should learn to read :p In this case, I don't see any corner case so that's probably the best way to handle sorting. Very cool idea!
