### ISSUE TITLE
🚨 Potential Path Traversal (CWE-22)

### ISSUE THREAD

**Issue by huntr-helper** [svenstaro/miniserve#518]
👋 Hello, @svenstaro - a potential high severity Path Traversal (CWE-22) vulnerability in your repository has been disclosed to us.

#### Next Steps

1️⃣  Visit **https://huntr.dev/bounties/1-other-svenstaro/miniserve** for more advisory information.

2️⃣  **[Sign-up](https://huntr.dev/)** to validate or speak to the researcher for more assistance.

3️⃣ Propose a patch or outsource it to our community - whoever fixes it gets paid.

---

#### Confused or need more help?

- Join us on our **[Discord](https://huntr.dev/discord)** and a member of our team will be happy to help! 🤗

- Speak to a member of our team: @JamieSlome

---

*This issue was automatically generated by [huntr.dev](https://huntr.dev) - a bug bounty board for securing open source code.*

**Comment by ritiksahni** [comment]
Hi @svenstaro

Could you please check this submission? - https://huntr.dev/bounties/1-other-svenstaro/miniserve

Thanks!

**Comment by SergioBenitez** [comment]
I was looking through this repository as I scoured the web for how Rust projects automate building CLI binaries and came across this issue. I can confirm the vulnerability and have mounted an attack. The issue is very serious, especially when run `-o` and `-u`, as it allows an attack to overwrite any file on the system. Even with `-u`, the consequences are dire: the user can upload any file to any path accessible by the system. Imagine uploading RC scripts or keys.

@svenstaro If you need a reproducible case, please let me know. Otherwise, I will disclose the vulnerability in due-time to help others who may be running this software.

**Comment by almielczarek** [comment]
I've solved this problem before in a personal project and wouldn't mind taking a swing at trying to put together a possible solution here.

**Comment by AlexanderPavlenko** [comment]
Does running miniserve in a Docker container mitigates this issue?

**Comment by almielczarek** [comment]
I have a fix sitting in a local branch on my computer. Not sure if I should push it given the nature of this vulnerability.

If either @SergioBenitez or @svenstaro want a copy of the fix to test, please let me know and I'll send it to you in private.

Otherwise if @svenstaro wants me to open a PR I can do that too.

**Comment by svenstaro** [comment]
I'd appreciate a PR on this.
