### ISSUE TITLE
Dependency qrcodegen causing error on install

### ISSUE THREAD

**Issue by ViktorWb** [svenstaro/miniserve#568]
Today, when installing miniserve I ran into the error:

```
   ...
   Compiling maud v0.22.2
   Compiling actix-multipart v0.3.0
   Compiling actix-web-httpauth v0.5.1
error[E0599]: no method named `to_svg_string` found for struct `QrCode` in the current scope
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/miniserve-0.14.0/src/listing.rs:247:26
    |
247 |                 .body(qr.to_svg_string(2)),
    |                          ^^^^^^^^^^^^^ method not found in `QrCode`
```
It seems that qrcodegen 1.7 contains some breaking changes. Found some discussions about the issue [here](https://github.com/nayuki/QR-Code-generator/issues/117).

**Comment by nayuki** [comment]
Sorry for the inconvenience I caused.

* Short-term fix: Pin [version 1.6.0](https://crates.io/crates/qrcodegen/1.6.0).
* Long-term fix: Copy qrcodegen-demo [`to_svg_string()`](https://github.com/nayuki/QR-Code-generator/blob/4d13c303dc878ffae8df6d0e0a7513fe860a092c/rust/examples/qrcodegen-demo.rs#L166-L192) into your project.

Going forward, I do not plan to reintroduce graphics export in the qrcodegen library because there are too many different graphics libraries, programming environments, and aesthetics options to possibly cater to.

**Comment by nasso** [comment]
For those looking for a way to install with cargo while this is getting fixed:

```
cargo install miniserve --locked
```

**Comment by svenstaro** [comment]
Fixed in master. :)
