### ISSUE TITLE
Divide tests/cli.rs into multiple files

### ISSUE THREAD

**Issue by KSXGitHub** [svenstaro/miniserve#85]
The more features `miniserve` provides, the longer the file get.

**Comment by svenstaro** [comment]
Yes, this should eventually be done.

**Comment by boastful-squirrel** [comment]
It's more like we'll eventually have to use the lib+bin approach, since, as far as I know, Rust does not support integration tests for binary crates.

**Comment by svenstaro** [comment]
Did you take a look a look at our current integration tests? Since those do
binary integration tests.

**Comment by KSXGitHub** [comment]
> Did you take a look a look at our current integration tests? Since those do binary integration tests.

Of course I did. What do you mean exactly?

**Comment by boastful-squirrel** [comment]
I think he was talking to me, I deleted my message since it wasn't really clear. I was talking about Rust being unable to do binary integration tests for binary crates. 

What I meant is that, **as far as I know**, Rust does not provide a way to access the "objects" of a binary crates. For instance, you can't create a test in the `tests` folder that would check that a certain method returns a certain `ContextualError`, because you won't be able to import `ContextualError`. For that, you would need a `lib.rs` as wrapper. You can test that the output of your process corresponds to what you expected though, which is what you're both doing right now and with is great.

**Comment by KSXGitHub** [comment]
@boastful-squirrel No known programming language in existence can achieve what you described. And integration tests weren't meant to do that either. Integration tests are meant to act as a user, use the program like a user, and expect to see what a user sees. So you are not meant to access `ContextualError` as a Rust objects, only as a string. For Rust objects, you should use unit tests.
