### ISSUE TITLE
Question: In src/errors.rs, why are ContextualErrorKind and ContextualError declared separately?

### ISSUE THREAD

**Issue by KSXGitHub** [svenstaro/miniserve#87]
In [`src/errors.rs`](https://github.com/svenstaro/miniserve/blob/4ddade5bb351b454ebc7c9d6ad69ea40549cf9b1/src/errors.rs), I see [`ContextualError`](https://github.com/svenstaro/miniserve/blob/4ddade5bb351b454ebc7c9d6ad69ea40549cf9b1/src/errors.rs#L67-L69) being a wrapper of `ContextualErrorKind`, is there a reason of this?

**Comment by svenstaro** [comment]
It's this pattern: https://rust-lang-nursery.github.io/failure/error-errorkind.html

**Comment by KSXGitHub** [comment]
Given its high maintenance cost, and its convoluted usage (`Err(ContextualError::new(ContextualErrorKind::<name>(...)))`), I don't see the advantage of this pattern.

**Comment by svenstaro** [comment]
@boastful-squirrel did this part so maybe they can provide some insight here.

**Comment by boastful-squirrel** [comment]
That's from when I was using `failure`'s `context()` method, see the link that @svenstaro posted. Now that I don't use the `context()` feature anymore, all methods could return a `ContextualErrorKind` and you could simply write `ContextualErrorKind::<name>` everywhere. 

The reason I didn't remove the `ContextualError` type yet is because I keep playing with `failure` to see if there is a way to have the errors the way they are now, but well, still not yet. 

So if @svenstaro agrees, we could totally drop those calls everywhere.

**Comment by svenstaro** [comment]
In that case, sure, go ahead.
